use sql_mgp_boffice;
DROP table if exists Transaksi_TT;
CREATE TABLE Transaksi_TT(
row_id				bigint NOT NULL AUTO_INCREMENT KEY,
id 					char(32),
id_owner 			char(32),
id_outlet		 	char(32),
id_karyawan			char(32),
id_kasir			char(32),
id_pelanggan		char(32),
id_meja				char(32),
id_promo			char(32),
id_diskon			char(32),
id_pajak			char(32),
id_service			char(32),
user_id				char(32),
nama_pemesan		char(50),
jenis_user			char(32),
total_modal			double,
total_transaksi		double,
total_bayar			double,
diskon				double,
pajak				double,
service				double,
is_paid				bit,
waktu_transaksi 	DATETIME,
modify_status 		CHAR(1) NULL,
last_modified_by 	VARCHAR(50) NULL,
last_modified_time 	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	UNIQUE INDEX `uidx_id` (id ASC),
    INDEX `idx_id_owner` (id_owner ASC)

);

DROP table if exists Transaksi_TH;
CREATE TABLE Transaksi_TH(
row_id				bigint NOT NULL AUTO_INCREMENT KEY,
id 					char(32),
id_transaksi		char(32),
id_owner 			char(32),
id_outlet		 	char(32),
id_karyawan			char(32),
id_kasir			char(32),
id_pelanggan		char(32),
id_meja				char(32),
id_promo			char(32),
id_diskon			char(32),
id_pajak			char(32),
id_service			char(32),
user_id				char(32),
nama_pemesan		char(50),
jenis_user			char(32),
total_modal			double,
total_transaksi		double,
total_bayar			double,
diskon				double,
pajak				double,
service				double,
is_paid				bit,
waktu_transaksi 	DATETIME,
proses				VARCHAR(50) NULL,
modify_status 		CHAR(1) NULL,
last_modified_by 	VARCHAR(50) NULL,
last_modified_time 	DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	UNIQUE INDEX `uidx_id` (id ASC),
    INDEX `idx_id_owner` (id_owner ASC)
)